#!/bin/bash
set -eu
BD="\x1b[1;33;4m"
NM="\x1b[0m"
DS="\x1b[37m"
DARK="\x1b[90m"

nocomments() {
    grep -Ev "^[[:space:]]*(#|$)" "$@"
}

pick_editor() {
    for e in "${VISUAL:-}" "${EDITOR:-}" vi nano vim; do
        [ -n "$e" ] && command -v "$e" >/dev/null 2>&1 && {
            printf '%s\n' "$e"
            return
        }
    done
}

editor=$(pick_editor)

while read -r pacnew <&5; do
    dirname=$(dirname "$pacnew")
    basename=$(basename -s .pacnew "$pacnew")
    active=$dirname/$basename
    pacstock=$dirname/$basename.pacstock
    pacsave=$dirname/$basename.pacsave
    pacnewbasename=$(basename "$pacnew")
    pacnewdirname=$(dirname "$pacnew")

    if [[ -f "${pacstock}" ]]; then
        if cmp "$pacnew" "$pacstock"; then
            echo "$pacnew is unchanged from $pacstock"
            (set -x; rm "$pacnew")
            continue
        fi
    fi

    if [[ ! -r "$active" || ! -w "$active" ]]; then
        echo "Skipping $pacnew: insufficient permissions to read/write $active"
        continue
    fi

    while true; do
        echo -en \
            "\n${pacnewdirname}/\x1b[32m${pacnewbasename}${NM}: ${BD}i${NM}nstall, ${BD}m${NM}ove, ${BD}r${NM}emove, ${BD}e${NM}dit, ${BD}s${NM}kip, ${BD}q${NM}uit, ${BD}d${NM}iff"
        if [[ -f "$pacstock" ]]; then
            echo -en ", ${BD}c${NM}hanges"
        fi
        echo -en ", ${BD}h${NM}elp${BD}?${NM} "


        read -rsn1 key <&0
        case "$key" in
            '?'|h)
                echo -e "\n\x1b[4mStatus${NM}:"
                echo -e "     current: ${active}"
                echo -e "      pacnew: ${pacnew}"
                if [[ -f "$pacstock" ]]; then
                    echo -e "    pacstock: ${pacstock}"
                else
                    echo -e "    pacstock: Not found"
                fi

                echo -e "\n\x1b[4mReview${NM}:"
                echo -e "     ${BD}d${NM}iff: show difference from current to .pacnew (${BD}D${NM} to hide comments)"
                if [[ -f "$pacstock" ]]; then
                    echo -e "  ${BD}c${NM}hanges: show changes from .pacstock to .pacnew (${BD}C${NM} to hide comments)"
                else
                    echo -e "  ${DARK}changes: show changes from .pacstock to .pacnew (.pacstock not found)${NM}"
                fi
                echo -e "\n\x1b[4mActions\x1b[0m:"
                echo -e "     ${BD}e${NM}dit: edit current configuration with $editor (${BD}E${NM} to edit .pacnew)"
                echo -e "  ${BD}i${NM}nstall: replace current configuration with .pacnew (current moved to .pacsave) (${BD}I${NM} to edit after install)"
                echo -e "     ${BD}m${NM}ove: move .pacnew to .pacstock (save it)"
                echo -e "   ${BD}r${NM}emove: delete .pacnew permanently"
                echo -e "     ${BD}s${NM}kip: skip for now"
                echo -e "     ${BD}q${NM}uit: abort"
                ;;

            e)
                (set -x;  ${editor} "$active") ||:
                ;;
            E)
                (set -x;  ${editor} "$pacnew") ||:
                ;;
            d)
                echo diff
                (set -x; diff --color=auto "$active" "$pacnew") ||:
                ;;
            D)
                echo diff
                (set -x; diff --color=auto <(nocomments "$active") <(nocomments "$pacnew")) ||:
                ;;
            c)
                echo changes
                (set -x; diff "$pacstock" "$pacnew") ||:
                ;;
            C)
                echo changes
                (set -x; diff <(nocomments "$pacstock") <(nocomments "$pacnew")) ||:
                ;;
            i)
                echo install
                (set -x; mv -i "$active" "$pacsave"; mv -i "$pacnew" "$active")
                break
                ;;
            I)
                echo install & edit
                (set -x; mv -i "$active" "$pacsave"; mv -i "$pacnew" "$active"; "$editor" "$active")
                break
                ;;
            m)
                echo move
                (set -x; mv "$pacnew" "$pacstock")
                break
                ;;
            r)
                echo remove
                (set -x; rm "$pacnew")
                break
                ;;
            s)
                echo skip
                break
                ;;
            q)
                echo quit
                exit 1
                ;;
            *)
                echo unknown
                ;;
        esac
    done
done 5< <(find /etc -name \*.pacnew -type f 2>/dev/null)
